# Generated by Django 4.1.3 on 2023-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuleuser',
            name='uid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
