# Generated by Django 4.1.3 on 2023-10-01 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capsuleapi', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfitIdTag', to='capsuleapi.outfit')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagId', to='capsuleapi.tag')),
            ],
        ),
    ]
